wandb_version: 1

name:
  desc: null
  value: run1
learning_rate:
  desc: null
  value: 0.0001
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721224570
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.17.4
      8:
      - 5
      - 9
      13: linux-x86_64
